// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'entities/custom_workstations.dart';
import 'entities/workstation_positions.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 1163650179154083951),
      name: 'WorkStation',
      lastPropertyId: const obx_int.IdUid(6, 8620826117761092948),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2303018469580053647),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5286223814925261784),
            name: 'workStationId',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3872039968497747103),
            name: 'left',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2400061961181691010),
            name: 'top',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 1240759268826325653),
            name: 'category',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8620826117761092948),
            name: 'filter',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1684346824670955740),
      name: 'CustomWorkStation',
      lastPropertyId: const obx_int.IdUid(7, 3019103563608802187),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 187070858540335802),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 3424080934583467209),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3540744041451946431),
            name: 'imagePath',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3883334057817626677),
            name: 'type',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3015291079867613970),
            name: 'status',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4310031686035310859),
            name: 'left',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 3019103563608802187),
            name: 'top',
            type: 8,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 1684346824670955740),
      lastIndexId: const obx_int.IdUid(0, 0),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    WorkStation: obx_int.EntityDefinition<WorkStation>(
        model: _entities[0],
        toOneRelations: (WorkStation object) => [],
        toManyRelations: (WorkStation object) => {},
        getId: (WorkStation object) => object.id,
        setId: (WorkStation object, int id) {
          object.id = id;
        },
        objectToFB: (WorkStation object, fb.Builder fbb) {
          final workStationIdOffset = object.workStationId == null
              ? null
              : fbb.writeString(object.workStationId!);
          final categoryOffset = fbb.writeString(object.category);
          final filterOffset = fbb.writeString(object.filter);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, workStationIdOffset);
          fbb.addFloat64(2, object.left);
          fbb.addFloat64(3, object.top);
          fbb.addOffset(4, categoryOffset);
          fbb.addOffset(5, filterOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final workStationIdParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 6);
          final leftParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final topParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final categoryParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final filterParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = WorkStation(
              id: idParam,
              workStationId: workStationIdParam,
              left: leftParam,
              top: topParam,
              category: categoryParam,
              filter: filterParam);

          return object;
        }),
    CustomWorkStation: obx_int.EntityDefinition<CustomWorkStation>(
        model: _entities[1],
        toOneRelations: (CustomWorkStation object) => [],
        toManyRelations: (CustomWorkStation object) => {},
        getId: (CustomWorkStation object) => object.id,
        setId: (CustomWorkStation object, int id) {
          object.id = id;
        },
        objectToFB: (CustomWorkStation object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final imagePathOffset = fbb.writeString(object.imagePath);
          final typeOffset = fbb.writeString(object.type);
          final statusOffset = fbb.writeString(object.status);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, imagePathOffset);
          fbb.addOffset(3, typeOffset);
          fbb.addOffset(4, statusOffset);
          fbb.addFloat64(5, object.left);
          fbb.addFloat64(6, object.top);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final imagePathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final typeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final statusParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final leftParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final topParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final object = CustomWorkStation(
              id: idParam,
              name: nameParam,
              imagePath: imagePathParam,
              type: typeParam,
              status: statusParam,
              left: leftParam,
              top: topParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [WorkStation] entity fields to define ObjectBox queries.
class WorkStation_ {
  /// see [WorkStation.id]
  static final id =
      obx.QueryIntegerProperty<WorkStation>(_entities[0].properties[0]);

  /// see [WorkStation.workStationId]
  static final workStationId =
      obx.QueryStringProperty<WorkStation>(_entities[0].properties[1]);

  /// see [WorkStation.left]
  static final left =
      obx.QueryDoubleProperty<WorkStation>(_entities[0].properties[2]);

  /// see [WorkStation.top]
  static final top =
      obx.QueryDoubleProperty<WorkStation>(_entities[0].properties[3]);

  /// see [WorkStation.category]
  static final category =
      obx.QueryStringProperty<WorkStation>(_entities[0].properties[4]);

  /// see [WorkStation.filter]
  static final filter =
      obx.QueryStringProperty<WorkStation>(_entities[0].properties[5]);
}

/// [CustomWorkStation] entity fields to define ObjectBox queries.
class CustomWorkStation_ {
  /// see [CustomWorkStation.id]
  static final id =
      obx.QueryIntegerProperty<CustomWorkStation>(_entities[1].properties[0]);

  /// see [CustomWorkStation.name]
  static final name =
      obx.QueryStringProperty<CustomWorkStation>(_entities[1].properties[1]);

  /// see [CustomWorkStation.imagePath]
  static final imagePath =
      obx.QueryStringProperty<CustomWorkStation>(_entities[1].properties[2]);

  /// see [CustomWorkStation.type]
  static final type =
      obx.QueryStringProperty<CustomWorkStation>(_entities[1].properties[3]);

  /// see [CustomWorkStation.status]
  static final status =
      obx.QueryStringProperty<CustomWorkStation>(_entities[1].properties[4]);

  /// see [CustomWorkStation.left]
  static final left =
      obx.QueryDoubleProperty<CustomWorkStation>(_entities[1].properties[5]);

  /// see [CustomWorkStation.top]
  static final top =
      obx.QueryDoubleProperty<CustomWorkStation>(_entities[1].properties[6]);
}
